version: '3'
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: CARINFOEM_DB
      POSTGRES_USER: carinfo_service
      POSTGRES_PASSWORD: 12345678
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_service"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  server:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres-data: