basePath: /
definitions:
  RegNums:
    properties:
      reg_num:
        example:
        - X123XX150
        items:
          type: string
        type: array
    type: object
  adder.AddResponse:
    properties:
      cars_id:
        items:
          type: integer
        type: array
      errors:
        items: {}
        type: array
      failed_cars:
        items:
          type: string
        type: array
    type: object
  car.Car:
    properties:
      mark:
        example: Lada
        type: string
      model:
        example: Vesta
        type: string
      owner:
        $ref: '#/definitions/car.People'
      regNum:
        example: X123XX150
        type: string
      year:
        example: 2001
        type: integer
    type: object
  car.CarWithOwner:
    properties:
      id:
        type: integer
      mark:
        type: string
      model:
        type: string
      owner:
        $ref: '#/definitions/car.People'
      regNum:
        type: string
      year:
        type: integer
    type: object
  car.People:
    properties:
      name:
        example: Ivan
        type: string
      patronymic:
        example: Ivanovich
        type: string
      surname:
        example: Ivanov
        type: string
    type: object
  err_response.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  getter.GetResponse:
    properties:
      carWithOwner:
        items:
          $ref: '#/definitions/car.CarWithOwner'
        type: array
      info:
        $ref: '#/definitions/getter.Info'
    type: object
  getter.Info:
    properties:
      last_page:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API server for obtaining information about the car
  title: CarInfo App API
  version: "1.0"
paths:
  /car/add:
    post:
      consumes:
      - application/json
      description: add car
      parameters:
      - description: Array of new car registration numbers
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/RegNums'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/adder.AddResponse'
        "206":
          description: Partial Content
          schema:
            $ref: '#/definitions/adder.AddResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err_response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err_response.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/err_response.Response'
      summary: Add
      tags:
      - car
  /car/delete/{id}:
    delete:
      consumes:
      - application/json
      description: delete car
      parameters:
      - description: Car ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err_response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/err_response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err_response.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/err_response.Response'
      summary: Delete
      tags:
      - car
  /car/patch/{id}:
    patch:
      consumes:
      - application/json
      description: patch car
      parameters:
      - description: Car ID
        in: path
        name: id
        required: true
        type: integer
      - description: new car data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/car.Car'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err_response.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/err_response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err_response.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/err_response.Response'
      summary: Patch
      tags:
      - car
  /cars:
    get:
      consumes:
      - application/json
      description: get cars
      parameters:
      - description: Page size (default is 100)
        in: query
        name: page_size
        type: integer
      - description: Page token (default is 1)
        in: query
        name: page_token
        type: integer
      - description: 'Filter by year (format: ''start:end'') example: 2000:2023'
        in: query
        name: year
        type: string
      - description: Filter by registration number
        in: query
        name: reg_num
        type: string
      - description: Filter by car model
        in: query
        name: model
        type: string
      - description: Filter by car mark
        in: query
        name: mark
        type: string
      - description: Filter by owner name
        in: query
        name: name
        type: string
      - description: Filter by owner surname
        in: query
        name: surname
        type: string
      - description: Filter by owner patronymic
        in: query
        name: patronymic
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/getter.GetResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err_response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err_response.Response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/err_response.Response'
      summary: Get
      tags:
      - cars
swagger: "2.0"
